// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjzs661WNWjpvfzQh2MTIo6jSxhkx52s8',
    appId: '1:15150088271:web:abe2ac389b861ca4a6ea3a',
    messagingSenderId: '15150088271',
    projectId: 'balikavi-431f9',
    authDomain: 'balikavi-431f9.firebaseapp.com',
    storageBucket: 'balikavi-431f9.appspot.com',
    measurementId: 'G-KRDTKS2LQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLgFFao__ZtWlQjlxI4YaUFb3wNF5qIvM',
    appId: '1:15150088271:android:4749fd5dc42ca46aa6ea3a',
    messagingSenderId: '15150088271',
    projectId: 'balikavi-431f9',
    storageBucket: 'balikavi-431f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ63t2QNEXo0akKMsECyvUFAH-RqKS8vo',
    appId: '1:15150088271:ios:09d656e7eec23e1ea6ea3a',
    messagingSenderId: '15150088271',
    projectId: 'balikavi-431f9',
    storageBucket: 'balikavi-431f9.appspot.com',
    iosClientId: '15150088271-nskurka55scrd8nc0fqj4pm6h1d35lqt.apps.googleusercontent.com',
    iosBundleId: 'com.balikavi.balikavi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ63t2QNEXo0akKMsECyvUFAH-RqKS8vo',
    appId: '1:15150088271:ios:09d656e7eec23e1ea6ea3a',
    messagingSenderId: '15150088271',
    projectId: 'balikavi-431f9',
    storageBucket: 'balikavi-431f9.appspot.com',
    iosClientId: '15150088271-nskurka55scrd8nc0fqj4pm6h1d35lqt.apps.googleusercontent.com',
    iosBundleId: 'com.balikavi.balikavi',
  );
}
